language: lisp

env: PREFIX="$(pwd)/sbcl"
     SBCL_HOME="$(pwd)/sbcl/lib/sbcl"
     SBCL="$(pwd)/sbcl/bin/sbcl"
     SBCL_OPTIONS="--noinform --no-userinit"

install:
  - curl -L sbcl.tar.bz2 "${SBCL_DOWNLOAD_URL}" | tar -xj
  - ( cd sbcl-* && INSTALL_ROOT="${PREFIX}" sh install.sh )

  - curl -o cl "${CL_LAUNCH_DOWNLOAD_URL}"
  - chmod +x cl

  - curl -o quicklisp.lisp "${QUICKLISP_DOWNLOAD_URL}"
  - ./cl -L quicklisp.lisp '(quicklisp-quickstart:install :path "quicklisp/")'

script:
  - ./cl
      -S '(:source-registry (:directory "'$(pwd)'") :ignore-inherited-configuration)'
      -e '(load "quicklisp/setup.lisp")'
      -e '(ql:quickload (list :specializable :specializable-test))'
      -e '(ql:quickload (list :language-extension.accept-specializer    :language-extension.accept-specializer-test))'
      -e '(ql:quickload (list :language-extension.cons-specializer      :language-extension.cons-specializer-test))'
      -e '(ql:quickload (list :language-extension.prototype-specializer :language-extension.prototype-specializer-test))'
      '(or (and (specializable-test:run-tests)
                (accept-specializer.test:run-tests)
                (cons-specializer.test:run-tests)
                (prototype-specializer.test:run-tests))
           (uiop:quit -1))'
